// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendMsgRequest struct {
	SenderUid            uint64   `protobuf:"varint,1,opt,name=senderUid,proto3" json:"senderUid,omitempty"`
	RecipientUid         uint64   `protobuf:"varint,2,opt,name=recipientUid,proto3" json:"recipientUid,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MsgType              int32    `protobuf:"varint,4,opt,name=msgType,proto3" json:"msgType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgRequest) Reset()         { *m = SendMsgRequest{} }
func (m *SendMsgRequest) String() string { return proto.CompactTextString(m) }
func (*SendMsgRequest) ProtoMessage()    {}
func (*SendMsgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *SendMsgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgRequest.Unmarshal(m, b)
}
func (m *SendMsgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgRequest.Marshal(b, m, deterministic)
}
func (m *SendMsgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgRequest.Merge(m, src)
}
func (m *SendMsgRequest) XXX_Size() int {
	return xxx_messageInfo_SendMsgRequest.Size(m)
}
func (m *SendMsgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgRequest proto.InternalMessageInfo

func (m *SendMsgRequest) GetSenderUid() uint64 {
	if m != nil {
		return m.SenderUid
	}
	return 0
}

func (m *SendMsgRequest) GetRecipientUid() uint64 {
	if m != nil {
		return m.RecipientUid
	}
	return 0
}

func (m *SendMsgRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SendMsgRequest) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

type QueryRecordFromRequest struct {
	OwnerUid             uint64   `protobuf:"varint,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	OtherUid             uint64   `protobuf:"varint,2,opt,name=otherUid,proto3" json:"otherUid,omitempty"`
	FromMid              uint64   `protobuf:"varint,3,opt,name=fromMid,proto3" json:"fromMid,omitempty"`
	Count                int64    `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRecordFromRequest) Reset()         { *m = QueryRecordFromRequest{} }
func (m *QueryRecordFromRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRecordFromRequest) ProtoMessage()    {}
func (*QueryRecordFromRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *QueryRecordFromRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRecordFromRequest.Unmarshal(m, b)
}
func (m *QueryRecordFromRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRecordFromRequest.Marshal(b, m, deterministic)
}
func (m *QueryRecordFromRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRecordFromRequest.Merge(m, src)
}
func (m *QueryRecordFromRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRecordFromRequest.Size(m)
}
func (m *QueryRecordFromRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRecordFromRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRecordFromRequest proto.InternalMessageInfo

func (m *QueryRecordFromRequest) GetOwnerUid() uint64 {
	if m != nil {
		return m.OwnerUid
	}
	return 0
}

func (m *QueryRecordFromRequest) GetOtherUid() uint64 {
	if m != nil {
		return m.OtherUid
	}
	return 0
}

func (m *QueryRecordFromRequest) GetFromMid() uint64 {
	if m != nil {
		return m.FromMid
	}
	return 0
}

func (m *QueryRecordFromRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryNewerMsgFromRequest struct {
	OwnerUid             uint64   `protobuf:"varint,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	OtherUid             uint64   `protobuf:"varint,2,opt,name=otherUid,proto3" json:"otherUid,omitempty"`
	FromMid              uint64   `protobuf:"varint,3,opt,name=fromMid,proto3" json:"fromMid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryNewerMsgFromRequest) Reset()         { *m = QueryNewerMsgFromRequest{} }
func (m *QueryNewerMsgFromRequest) String() string { return proto.CompactTextString(m) }
func (*QueryNewerMsgFromRequest) ProtoMessage()    {}
func (*QueryNewerMsgFromRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *QueryNewerMsgFromRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryNewerMsgFromRequest.Unmarshal(m, b)
}
func (m *QueryNewerMsgFromRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryNewerMsgFromRequest.Marshal(b, m, deterministic)
}
func (m *QueryNewerMsgFromRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryNewerMsgFromRequest.Merge(m, src)
}
func (m *QueryNewerMsgFromRequest) XXX_Size() int {
	return xxx_messageInfo_QueryNewerMsgFromRequest.Size(m)
}
func (m *QueryNewerMsgFromRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryNewerMsgFromRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryNewerMsgFromRequest proto.InternalMessageInfo

func (m *QueryNewerMsgFromRequest) GetOwnerUid() uint64 {
	if m != nil {
		return m.OwnerUid
	}
	return 0
}

func (m *QueryNewerMsgFromRequest) GetOtherUid() uint64 {
	if m != nil {
		return m.OtherUid
	}
	return 0
}

func (m *QueryNewerMsgFromRequest) GetFromMid() uint64 {
	if m != nil {
		return m.FromMid
	}
	return 0
}

type QueryContactsRequest struct {
	OwnerUid             uint64   `protobuf:"varint,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryContactsRequest) Reset()         { *m = QueryContactsRequest{} }
func (m *QueryContactsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryContactsRequest) ProtoMessage()    {}
func (*QueryContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *QueryContactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryContactsRequest.Unmarshal(m, b)
}
func (m *QueryContactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryContactsRequest.Marshal(b, m, deterministic)
}
func (m *QueryContactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryContactsRequest.Merge(m, src)
}
func (m *QueryContactsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryContactsRequest.Size(m)
}
func (m *QueryContactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryContactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryContactsRequest proto.InternalMessageInfo

func (m *QueryContactsRequest) GetOwnerUid() uint64 {
	if m != nil {
		return m.OwnerUid
	}
	return 0
}

type QueryTotalUnreadRequest struct {
	OwnerUid             uint64   `protobuf:"varint,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTotalUnreadRequest) Reset()         { *m = QueryTotalUnreadRequest{} }
func (m *QueryTotalUnreadRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTotalUnreadRequest) ProtoMessage()    {}
func (*QueryTotalUnreadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *QueryTotalUnreadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTotalUnreadRequest.Unmarshal(m, b)
}
func (m *QueryTotalUnreadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTotalUnreadRequest.Marshal(b, m, deterministic)
}
func (m *QueryTotalUnreadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTotalUnreadRequest.Merge(m, src)
}
func (m *QueryTotalUnreadRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTotalUnreadRequest.Size(m)
}
func (m *QueryTotalUnreadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTotalUnreadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTotalUnreadRequest proto.InternalMessageInfo

func (m *QueryTotalUnreadRequest) GetOwnerUid() uint64 {
	if m != nil {
		return m.OwnerUid
	}
	return 0
}

type MessagesResponse struct {
	List                 []*MessageResponse `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MessagesResponse) Reset()         { *m = MessagesResponse{} }
func (m *MessagesResponse) String() string { return proto.CompactTextString(m) }
func (*MessagesResponse) ProtoMessage()    {}
func (*MessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *MessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagesResponse.Unmarshal(m, b)
}
func (m *MessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagesResponse.Marshal(b, m, deterministic)
}
func (m *MessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagesResponse.Merge(m, src)
}
func (m *MessagesResponse) XXX_Size() int {
	return xxx_messageInfo_MessagesResponse.Size(m)
}
func (m *MessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessagesResponse proto.InternalMessageInfo

func (m *MessagesResponse) GetList() []*MessageResponse {
	if m != nil {
		return m.List
	}
	return nil
}

type MessageResponse struct {
	Mid                  uint64   `protobuf:"varint,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	OwnerUid             uint64   `protobuf:"varint,3,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	OtherUid             uint64   `protobuf:"varint,5,opt,name=otherUid,proto3" json:"otherUid,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=createTime,proto3" json:"createTime,omitempty"`
	OwnerUidAvatar       string   `protobuf:"bytes,7,opt,name=ownerUidAvatar,proto3" json:"ownerUidAvatar,omitempty"`
	OtherUidAvatar       string   `protobuf:"bytes,8,opt,name=otherUidAvatar,proto3" json:"otherUidAvatar,omitempty"`
	OwnerName            string   `protobuf:"bytes,9,opt,name=ownerName,proto3" json:"ownerName,omitempty"`
	OtherName            string   `protobuf:"bytes,10,opt,name=otherName,proto3" json:"otherName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetMid() uint64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *MessageResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MessageResponse) GetOwnerUid() uint64 {
	if m != nil {
		return m.OwnerUid
	}
	return 0
}

func (m *MessageResponse) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MessageResponse) GetOtherUid() uint64 {
	if m != nil {
		return m.OtherUid
	}
	return 0
}

func (m *MessageResponse) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *MessageResponse) GetOwnerUidAvatar() string {
	if m != nil {
		return m.OwnerUidAvatar
	}
	return ""
}

func (m *MessageResponse) GetOtherUidAvatar() string {
	if m != nil {
		return m.OtherUidAvatar
	}
	return ""
}

func (m *MessageResponse) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *MessageResponse) GetOtherName() string {
	if m != nil {
		return m.OtherName
	}
	return ""
}

type MessageContactResponse struct {
	OwnerUid             uint64         `protobuf:"varint,1,opt,name=ownerUid,proto3" json:"ownerUid,omitempty"`
	OwnerAvatar          string         `protobuf:"bytes,2,opt,name=ownerAvatar,proto3" json:"ownerAvatar,omitempty"`
	OwnerName            string         `protobuf:"bytes,3,opt,name=ownerName,proto3" json:"ownerName,omitempty"`
	TotalUnread          int64          `protobuf:"varint,4,opt,name=totalUnread,proto3" json:"totalUnread,omitempty"`
	ContactInfoList      []*ContactInfo `protobuf:"bytes,5,rep,name=contactInfoList,proto3" json:"contactInfoList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MessageContactResponse) Reset()         { *m = MessageContactResponse{} }
func (m *MessageContactResponse) String() string { return proto.CompactTextString(m) }
func (*MessageContactResponse) ProtoMessage()    {}
func (*MessageContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *MessageContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageContactResponse.Unmarshal(m, b)
}
func (m *MessageContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageContactResponse.Marshal(b, m, deterministic)
}
func (m *MessageContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageContactResponse.Merge(m, src)
}
func (m *MessageContactResponse) XXX_Size() int {
	return xxx_messageInfo_MessageContactResponse.Size(m)
}
func (m *MessageContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageContactResponse proto.InternalMessageInfo

func (m *MessageContactResponse) GetOwnerUid() uint64 {
	if m != nil {
		return m.OwnerUid
	}
	return 0
}

func (m *MessageContactResponse) GetOwnerAvatar() string {
	if m != nil {
		return m.OwnerAvatar
	}
	return ""
}

func (m *MessageContactResponse) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *MessageContactResponse) GetTotalUnread() int64 {
	if m != nil {
		return m.TotalUnread
	}
	return 0
}

func (m *MessageContactResponse) GetContactInfoList() []*ContactInfo {
	if m != nil {
		return m.ContactInfoList
	}
	return nil
}

type ContactInfo struct {
	OtherUid             uint64   `protobuf:"varint,1,opt,name=otherUid,proto3" json:"otherUid,omitempty"`
	OtherName            string   `protobuf:"bytes,2,opt,name=otherName,proto3" json:"otherName,omitempty"`
	OtherAvatar          string   `protobuf:"bytes,3,opt,name=otherAvatar,proto3" json:"otherAvatar,omitempty"`
	Mid                  uint64   `protobuf:"varint,4,opt,name=mid,proto3" json:"mid,omitempty"`
	Type                 int32    `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	ConvUnread           int64    `protobuf:"varint,7,opt,name=convUnread,proto3" json:"convUnread,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactInfo) Reset()         { *m = ContactInfo{} }
func (m *ContactInfo) String() string { return proto.CompactTextString(m) }
func (*ContactInfo) ProtoMessage()    {}
func (*ContactInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *ContactInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactInfo.Unmarshal(m, b)
}
func (m *ContactInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactInfo.Marshal(b, m, deterministic)
}
func (m *ContactInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactInfo.Merge(m, src)
}
func (m *ContactInfo) XXX_Size() int {
	return xxx_messageInfo_ContactInfo.Size(m)
}
func (m *ContactInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ContactInfo proto.InternalMessageInfo

func (m *ContactInfo) GetOtherUid() uint64 {
	if m != nil {
		return m.OtherUid
	}
	return 0
}

func (m *ContactInfo) GetOtherName() string {
	if m != nil {
		return m.OtherName
	}
	return ""
}

func (m *ContactInfo) GetOtherAvatar() string {
	if m != nil {
		return m.OtherAvatar
	}
	return ""
}

func (m *ContactInfo) GetMid() uint64 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *ContactInfo) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ContactInfo) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ContactInfo) GetConvUnread() int64 {
	if m != nil {
		return m.ConvUnread
	}
	return 0
}

func (m *ContactInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

type UnreadResponse struct {
	Unread               uint64   `protobuf:"varint,1,opt,name=unread,proto3" json:"unread,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnreadResponse) Reset()         { *m = UnreadResponse{} }
func (m *UnreadResponse) String() string { return proto.CompactTextString(m) }
func (*UnreadResponse) ProtoMessage()    {}
func (*UnreadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *UnreadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnreadResponse.Unmarshal(m, b)
}
func (m *UnreadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnreadResponse.Marshal(b, m, deterministic)
}
func (m *UnreadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnreadResponse.Merge(m, src)
}
func (m *UnreadResponse) XXX_Size() int {
	return xxx_messageInfo_UnreadResponse.Size(m)
}
func (m *UnreadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnreadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnreadResponse proto.InternalMessageInfo

func (m *UnreadResponse) GetUnread() uint64 {
	if m != nil {
		return m.Unread
	}
	return 0
}

func init() {
	proto.RegisterType((*SendMsgRequest)(nil), "SendMsgRequest")
	proto.RegisterType((*QueryRecordFromRequest)(nil), "QueryRecordFromRequest")
	proto.RegisterType((*QueryNewerMsgFromRequest)(nil), "QueryNewerMsgFromRequest")
	proto.RegisterType((*QueryContactsRequest)(nil), "QueryContactsRequest")
	proto.RegisterType((*QueryTotalUnreadRequest)(nil), "QueryTotalUnreadRequest")
	proto.RegisterType((*MessagesResponse)(nil), "MessagesResponse")
	proto.RegisterType((*MessageResponse)(nil), "MessageResponse")
	proto.RegisterType((*MessageContactResponse)(nil), "MessageContactResponse")
	proto.RegisterType((*ContactInfo)(nil), "ContactInfo")
	proto.RegisterType((*UnreadResponse)(nil), "UnreadResponse")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0x7e, 0xfa, 0x77, 0xba, 0xb5, 0x9d, 0x35, 0xda, 0x50, 0x21, 0x14, 0x59, 0x08, 0xf5,
	0xca, 0x17, 0x45, 0x20, 0xee, 0xd0, 0x54, 0x09, 0x09, 0x89, 0x4e, 0x22, 0x74, 0x0f, 0x10, 0x12,
	0xaf, 0x44, 0x6a, 0xec, 0x12, 0xbb, 0x9b, 0x76, 0xc7, 0x15, 0x6f, 0xc4, 0x13, 0x70, 0xcf, 0x7b,
	0xf0, 0x16, 0x28, 0x8e, 0xd3, 0x24, 0x5e, 0x87, 0x76, 0xc3, 0x5d, 0xce, 0x77, 0x8e, 0xed, 0xcf,
	0xe7, 0x7c, 0xfe, 0x02, 0xa7, 0x29, 0x15, 0x22, 0xdc, 0x50, 0xb2, 0xcb, 0xb8, 0xe4, 0xf8, 0x87,
	0x05, 0xc3, 0xcf, 0x94, 0xc5, 0x2b, 0xb1, 0x09, 0xe8, 0xb7, 0x3d, 0x15, 0x12, 0x3d, 0x83, 0xbe,
	0xa0, 0x2c, 0xa6, 0xd9, 0x55, 0x12, 0x7b, 0x96, 0x6f, 0xcd, 0xdd, 0xa0, 0x02, 0x10, 0x86, 0x93,
	0x8c, 0x46, 0xc9, 0x2e, 0xa1, 0x4c, 0xe6, 0x05, 0xb6, 0x2a, 0x68, 0x60, 0xc8, 0x83, 0x6e, 0xc4,
	0x99, 0xa4, 0x4c, 0x7a, 0x8e, 0x6f, 0xcd, 0xfb, 0x41, 0x19, 0xe6, 0x99, 0x54, 0x6c, 0xd6, 0x77,
	0x3b, 0xea, 0xb9, 0xbe, 0x35, 0x6f, 0x07, 0x65, 0x88, 0xbf, 0x5b, 0x30, 0xf9, 0xb4, 0xa7, 0xd9,
	0x5d, 0x40, 0x23, 0x9e, 0xc5, 0xef, 0x33, 0x9e, 0x96, 0x84, 0x66, 0xd0, 0xe3, 0xb7, 0xac, 0xce,
	0xe7, 0x10, 0xab, 0x9c, 0xfc, 0x5a, 0xe4, 0x6c, 0x9d, 0xd3, 0x71, 0x7e, 0xd8, 0x75, 0xc6, 0xd3,
	0x55, 0x12, 0x2b, 0x1a, 0x6e, 0x50, 0x86, 0xe8, 0x1c, 0xda, 0x11, 0xdf, 0x33, 0xa9, 0x48, 0x38,
	0x41, 0x11, 0xe0, 0x2d, 0x78, 0x8a, 0xc1, 0x25, 0xbd, 0xa5, 0xd9, 0x4a, 0x6c, 0xfe, 0x2b, 0x07,
	0xbc, 0x80, 0x73, 0x75, 0xda, 0x92, 0x33, 0x19, 0x46, 0x52, 0x3c, 0xe2, 0x24, 0xfc, 0x1a, 0xa6,
	0x6a, 0xcd, 0x9a, 0xcb, 0x70, 0x7b, 0xc5, 0x32, 0x1a, 0xc6, 0x8f, 0x59, 0xf6, 0x16, 0xc6, 0xab,
	0x62, 0xea, 0x22, 0xa0, 0x62, 0xc7, 0x99, 0xa0, 0xe8, 0x05, 0xb8, 0xdb, 0x44, 0x48, 0xcf, 0xf2,
	0x9d, 0xf9, 0x60, 0x31, 0x26, 0xba, 0xa0, 0xcc, 0x07, 0x2a, 0x8b, 0x7f, 0xda, 0x30, 0x32, 0x32,
	0x68, 0x0c, 0x4e, 0x7a, 0x38, 0x24, 0xff, 0xac, 0xcf, 0xdb, 0x6e, 0xce, 0xbb, 0xce, 0xca, 0x31,
	0xda, 0x86, 0xc0, 0x95, 0x95, 0x10, 0xd4, 0x77, 0xa3, 0x95, 0x6d, 0xa3, 0x95, 0xcf, 0x01, 0xa2,
	0x8c, 0x86, 0x92, 0xae, 0x93, 0x94, 0x7a, 0x1d, 0x35, 0xb9, 0x1a, 0x82, 0x5e, 0xc2, 0xb0, 0xdc,
	0xfb, 0xe2, 0x26, 0x94, 0x61, 0xe6, 0x75, 0x15, 0x19, 0x03, 0x55, 0x75, 0x7a, 0x4f, 0x5d, 0xd7,
	0xd3, 0x75, 0x0d, 0x34, 0x7f, 0x07, 0x6a, 0xe5, 0x65, 0x98, 0x52, 0xaf, 0xaf, 0x4a, 0x2a, 0x40,
	0x65, 0xf3, 0x7a, 0x95, 0x05, 0x9d, 0x2d, 0x01, 0xfc, 0xdb, 0x82, 0x89, 0xee, 0x9b, 0x9e, 0xef,
	0xa1, 0x7d, 0xff, 0x52, 0x92, 0x0f, 0x03, 0xf5, 0xad, 0x79, 0x15, 0xcd, 0xac, 0x43, 0x4d, 0x52,
	0x8e, 0x49, 0xca, 0x87, 0x81, 0xac, 0xa4, 0xa1, 0xd5, 0x5d, 0x87, 0xd0, 0x1b, 0x18, 0x45, 0x05,
	0xa1, 0x0f, 0xec, 0x9a, 0x7f, 0xcc, 0x15, 0xd0, 0x56, 0x0a, 0x38, 0x21, 0xcb, 0x0a, 0x0f, 0xcc,
	0x22, 0xfc, 0xc7, 0x82, 0x41, 0xad, 0xa0, 0x31, 0x28, 0xcb, 0x18, 0x54, 0xa3, 0x35, 0xb6, 0xd1,
	0x1a, 0x75, 0xc7, 0x3c, 0xd0, 0x77, 0x74, 0xf4, 0x1d, 0x2b, 0xa8, 0x14, 0x98, 0x5b, 0x09, 0xac,
	0x94, 0x4a, 0xbb, 0x26, 0x95, 0x9a, 0xe8, 0x3a, 0x4d, 0xd1, 0xe5, 0x42, 0xe1, 0xec, 0x46, 0x37,
	0xa1, 0xab, 0x85, 0x72, 0x40, 0x0c, 0x21, 0xf5, 0x4c, 0x21, 0xe1, 0x39, 0x0c, 0xcb, 0xb7, 0xa5,
	0x67, 0x36, 0x81, 0xce, 0xbe, 0xd8, 0xad, 0xb8, 0xab, 0x8e, 0x16, 0xbf, 0x6c, 0xe8, 0xea, 0x31,
	0x23, 0x02, 0x5d, 0x6d, 0xa4, 0x68, 0x44, 0x9a, 0x96, 0x3a, 0xbb, 0xf7, 0xbc, 0x70, 0x0b, 0xbd,
	0x83, 0x91, 0xe1, 0x77, 0x68, 0x4a, 0x8e, 0x3b, 0xe0, 0xec, 0x8c, 0x98, 0xef, 0x17, 0xb7, 0xd0,
	0x12, 0xce, 0xee, 0xd9, 0x15, 0x7a, 0x4a, 0x1e, 0xb2, 0xb0, 0xe3, 0x9b, 0x5c, 0xc0, 0x69, 0xc3,
	0x85, 0xd0, 0x13, 0x72, 0xcc, 0x95, 0x66, 0x53, 0x72, 0x5c, 0xce, 0xea, 0x22, 0x63, 0xd3, 0x94,
	0x90, 0x47, 0x1e, 0xf0, 0xa9, 0xd9, 0x88, 0x34, 0x7b, 0x8b, 0x5b, 0x5f, 0x3a, 0xea, 0x57, 0xf4,
	0xea, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x32, 0x97, 0xfc, 0x71, 0x9b, 0x06, 0x00, 0x00,
}
